# Loading train data

In [3]:
import pandas as pd
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
%matplotlib inline
train_data = pd.read_csv("train.csv")

In [4]:
train_data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [5]:
train_data.shape

(8523, 12)

In [6]:
train_data.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [7]:
train_data.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

#### Item_Weigth and Outlet_Size having null values . Item_Weigth is

In [8]:
train_data.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [9]:
cat_columns = [ 'Item_Fat_Content', 
       'Item_Type', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type']
for val in  cat_columns:
    print(train_data[val].unique(),"***********",val)

['Low Fat' 'Regular' 'low fat' 'LF' 'reg'] *********** Item_Fat_Content
['Dairy' 'Soft Drinks' 'Meat' 'Fruits and Vegetables' 'Household'
 'Baking Goods' 'Snack Foods' 'Frozen Foods' 'Breakfast'
 'Health and Hygiene' 'Hard Drinks' 'Canned' 'Breads' 'Starchy Foods'
 'Others' 'Seafood'] *********** Item_Type
['OUT049' 'OUT018' 'OUT010' 'OUT013' 'OUT027' 'OUT045' 'OUT017' 'OUT046'
 'OUT035' 'OUT019'] *********** Outlet_Identifier
[1999 2009 1998 1987 1985 2002 2007 1997 2004] *********** Outlet_Establishment_Year
['Medium' nan 'High' 'Small'] *********** Outlet_Size
['Tier 1' 'Tier 3' 'Tier 2'] *********** Outlet_Location_Type
['Supermarket Type1' 'Supermarket Type2' 'Grocery Store'
 'Supermarket Type3'] *********** Outlet_Type

# Handling the null values of columns

In [10]:
train_data["Outlet_Size"].fillna(train_data["Outlet_Size"].mode()[0],inplace=True)

In [11]:
train_data["Item_Weight"].fillna(train_data["Item_Weight"].mean(),inplace=True)

In [12]:
train_data["Outlet_Establishment_Year"] =train_data["Outlet_Establishment_Year"].astype(str)

# Preprocessing categorical feature

In [13]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

cat_columns = [ 'Item_Fat_Content', 
       'Item_Type', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type']

for val in  cat_columns:
    train_data[val]=label_encoder.fit_transform(train_data[val])

In [14]:
X= train_data.drop(columns=["Item_Identifier","Item_Outlet_Sales"])
y= train_data["Item_Outlet_Sales"]
X_train,X_cv,y_train,y_cv = train_test_split(X,y,random_state=10,test_size=0.2)

In [19]:
X_train.shape

(6818, 10)

# Model Building

In [55]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout
from keras.callbacks import EarlyStopping

In [56]:
# Build the Keras model
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
model = Sequential()
model.add(Dense(128, input_dim=10, activation='relu'))
#model.add(Dropout(0.5))  # Add dropout for regularization
model.add(Dense(64, activation='relu'))
#model.add(Dropout(0.3))  # Add dropout for regularization
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='linear'))   # Output layer with linear activation for regression

# Compile the model
model.compile(loss='mean_squared_error', optimizer='adam',metrics=['mae', 'mape'])

# Train the model
model.fit(X_train, y_train, epochs=200, batch_size=16, validation_data=(X_cv, y_cv),callbacks=[early_stopping])

Epoch 1/200
427/427 [==============================] - 3s 4ms/step - loss: 2933064.5000 - mae: 1232.8472 - mape: 137.4841 - val_loss: 1892341.5000 - val_mae: 1030.9164 - val_mape: 157.3933
Epoch 2/200
427/427 [==============================] - 1s 3ms/step - loss: 1930394.7500 - mae: 1026.1442 - mape: 145.2298 - val_loss: 1829333.6250 - val_mae: 990.7149 - val_mape: 131.6454
Epoch 3/200
427/427 [==============================] - 1s 3ms/step - loss: 1841045.1250 - mae: 1002.0168 - mape: 135.7269 - val_loss: 1770386.0000 - val_mae: 1003.0430 - val_mape: 146.5498
Epoch 4/200
427/427 [==============================] - 1s 3ms/step - loss: 1725346.2500 - mae: 972.9648 - mape: 123.1899 - val_loss: 1658895.7500 - val_mae: 979.9299 - val_mape: 133.1014
Epoch 5/200
427/427 [==============================] - 1s 3ms/step - loss: 1616959.6250 - mae: 953.4192 - mape: 110.6982 - val_loss: 1517218.5000 - val_mae: 931.6189 - val_mape: 109.3948
Epoch 6/200
427/427 [==============================] - 1s 3ms/step - loss: 1542260.3750 - mae: 932.1066 - mape: 100.3283 - val_loss: 1473318.6250 - val_mae: 905.6071 - val_mape: 94.0968
Epoch 7/200
427/427 [==============================] - 1s 3ms/step - loss: 1519166.1250 - mae: 926.1223 - mape: 96.3877 - val_loss: 1459906.0000 - val_mae: 893.7153 - val_mape: 86.6391
Epoch 8/200
427/427 [==============================] - 1s 3ms/step - loss: 1491994.6250 - mae: 915.2548 - mape: 92.2720 - val_loss: 1485938.5000 - val_mae: 928.6922 - val_mape: 102.0024
Epoch 9/200
427/427 [==============================] - 1s 3ms/step - loss: 1461127.0000 - mae: 902.6623 - mape: 89.5763 - val_loss: 1678323.8750 - val_mae: 916.4354 - val_mape: 64.5330
Epoch 10/200
427/427 [==============================] - 1s 3ms/step - loss: 1450383.7500 - mae: 894.9800 - mape: 85.5731 - val_loss: 1418505.1250 - val_mae: 871.1312 - val_mape: 76.8519
Epoch 11/200
427/427 [==============================] - 1s 3ms/step - loss: 1424423.3750 - mae: 884.6481 - mape: 82.4754 - val_loss: 1384197.7500 - val_mae: 867.8305 - val_mape: 80.0152
Epoch 12/200
427/427 [==============================] - 1s 3ms/step - loss: 1400959.0000 - mae: 873.8129 - mape: 80.7156 - val_loss: 1365881.1250 - val_mae: 851.2213 - val_mape: 73.1311
Epoch 13/200
427/427 [==============================] - 1s 3ms/step - loss: 1381685.8750 - mae: 864.1843 - mape: 77.7367 - val_loss: 1342482.3750 - val_mae: 850.6130 - val_mape: 76.8278
Epoch 14/200
427/427 [==============================] - 1s 3ms/step - loss: 1370556.8750 - mae: 856.5102 - mape: 74.7322 - val_loss: 1381735.8750 - val_mae: 877.7704 - val_mape: 87.5169
Epoch 15/200
427/427 [==============================] - 1s 3ms/step - loss: 1341344.6250 - mae: 844.4272 - mape: 72.8376 - val_loss: 1307724.1250 - val_mae: 838.5012 - val_mape: 75.6168
Epoch 16/200
427/427 [==============================] - 1s 3ms/step - loss: 1333248.6250 - mae: 835.5406 - mape: 70.6026 - val_loss: 1290568.8750 - val_mae: 827.1858 - val_mape: 71.5935
Epoch 17/200
427/427 [==============================] - 1s 3ms/step - loss: 1307300.0000 - mae: 825.2585 - mape: 67.7670 - val_loss: 1277278.0000 - val_mae: 817.5535 - val_mape: 69.2938
Epoch 18/200
427/427 [==============================] - 1s 3ms/step - loss: 1284646.5000 - mae: 813.6251 - mape: 65.7497 - val_loss: 1333584.7500 - val_mae: 804.9891 - val_mape: 53.2283
Epoch 19/200
427/427 [==============================] - 1s 3ms/step - loss: 1288596.6250 - mae: 810.7978 - mape: 63.6828 - val_loss: 1247109.1250 - val_mae: 803.3139 - val_mape: 65.0102
Epoch 20/200
427/427 [==============================] - 1s 3ms/step - loss: 1263902.0000 - mae: 800.5263 - mape: 62.3341 - val_loss: 1232194.2500 - val_mae: 794.8960 - val_mape: 63.6562
Epoch 21/200
427/427 [==============================] - 1s 3ms/step - loss: 1247089.0000 - mae: 793.6324 - mape: 60.1946 - val_loss: 1212029.2500 - val_mae: 776.0335 - val_mape: 56.5271
Epoch 22/200
427/427 [==============================] - 1s 3ms/step - loss: 1234884.6250 - mae: 787.9413 - mape: 59.2508 - val_loss: 1198850.5000 - val_mae: 773.2570 - val_mape: 57.4211
Epoch 23/200
427/427 [==============================] - 1s 3ms/step - loss: 1236584.5000 - mae: 785.4518 - mape: 59.3128 - val_loss: 1224727.2500 - val_mae: 771.8117 - val_mape: 53.4492
Epoch 24/200
427/427 [==============================] - 1s 3ms/step - loss: 1224820.1250 - mae: 781.5378 - mape: 58.3239 - val_loss: 1223616.1250 - val_mae: 791.0966 - val_mape: 64.8067
Epoch 25/200
427/427 [==============================] - 1s 2ms/step - loss: 1223145.0000 - mae: 781.6470 - mape: 58.4692 - val_loss: 1276160.7500 - val_mae: 820.0651 - val_mape: 72.5551
Epoch 26/200
427/427 [==============================] - 1s 3ms/step - loss: 1222886.3750 - mae: 780.9197 - mape: 58.3545 - val_loss: 1184040.1250 - val_mae: 763.4592 - val_mape: 53.3995
Epoch 27/200
427/427 [==============================] - 1s 2ms/step - loss: 1219025.2500 - mae: 776.1259 - mape: 58.0619 - val_loss: 1173433.6250 - val_mae: 767.1397 - val_mape: 61.1448
Epoch 28/200
427/427 [==============================] - 1s 3ms/step - loss: 1204711.2500 - mae: 772.8046 - mape: 57.7750 - val_loss: 1172819.7500 - val_mae: 765.4394 - val_mape: 59.9584
Epoch 29/200
427/427 [==============================] - 1s 3ms/step - loss: 1212294.7500 - mae: 773.6389 - mape: 57.1236 - val_loss: 1179692.5000 - val_mae: 771.0835 - val_mape: 62.1532
Epoch 30/200
427/427 [==============================] - 1s 3ms/step - loss: 1197890.7500 - mae: 771.6357 - mape: 57.6695 - val_loss: 1187775.2500 - val_mae: 775.7386 - val_mape: 61.9347
Epoch 31/200
427/427 [==============================] - 1s 3ms/step - loss: 1210116.6250 - mae: 774.8946 - mape: 57.6882 - val_loss: 1163110.3750 - val_mae: 757.5452 - val_mape: 55.0715
Epoch 32/200
427/427 [==============================] - 1s 3ms/step - loss: 1196117.1250 - mae: 769.1429 - mape: 56.4989 - val_loss: 1164649.7500 - val_mae: 764.0822 - val_mape: 60.5412
Epoch 33/200
427/427 [==============================] - 1s 3ms/step - loss: 1191699.1250 - mae: 765.9287 - mape: 56.7305 - val_loss: 1170126.6250 - val_mae: 755.4372 - val_mape: 52.1822
Epoch 34/200
427/427 [==============================] - 1s 3ms/step - loss: 1195834.3750 - mae: 768.7001 - mape: 56.8355 - val_loss: 1161114.7500 - val_mae: 753.7861 - val_mape: 54.0583
Epoch 35/200
427/427 [==============================] - 1s 2ms/step - loss: 1190172.2500 - mae: 764.8687 - mape: 55.8583 - val_loss: 1168778.8750 - val_mae: 772.5651 - val_mape: 64.9130
Epoch 36/200
427/427 [==============================] - 1s 3ms/step - loss: 1192118.0000 - mae: 767.0337 - mape: 56.7141 - val_loss: 1173069.5000 - val_mae: 753.3434 - val_mape: 52.3276
Epoch 37/200
427/427 [==============================] - 1s 3ms/step - loss: 1186987.7500 - mae: 766.9678 - mape: 56.3341 - val_loss: 1157087.1250 - val_mae: 753.3011 - val_mape: 54.4682
Epoch 38/200
427/427 [==============================] - 1s 3ms/step - loss: 1187667.0000 - mae: 767.6823 - mape: 56.3500 - val_loss: 1150450.8750 - val_mae: 751.3464 - val_mape: 53.7805
Epoch 39/200
427/427 [==============================] - 1s 3ms/step - loss: 1183054.1250 - mae: 764.2914 - mape: 55.4608 - val_loss: 1186028.2500 - val_mae: 786.8175 - val_mape: 68.6105
Epoch 40/200
427/427 [==============================] - 1s 3ms/step - loss: 1187579.2500 - mae: 764.4109 - mape: 56.4290 - val_loss: 1164508.7500 - val_mae: 754.9697 - val_mape: 52.0974
Epoch 41/200
427/427 [==============================] - 1s 3ms/step - loss: 1188386.0000 - mae: 765.8501 - mape: 56.1907 - val_loss: 1146966.7500 - val_mae: 754.3089 - val_mape: 56.5213
Epoch 42/200
427/427 [==============================] - 1s 2ms/step - loss: 1185823.7500 - mae: 764.5729 - mape: 55.4955 - val_loss: 1155843.3750 - val_mae: 756.8115 - val_mape: 55.6565
Epoch 43/200
427/427 [==============================] - 1s 3ms/step - loss: 1180066.3750 - mae: 764.0104 - mape: 55.8982 - val_loss: 1146930.8750 - val_mae: 752.5164 - val_mape: 54.8036
Epoch 44/200
427/427 [==============================] - 1s 2ms/step - loss: 1169368.7500 - mae: 758.4341 - mape: 55.0019 - val_loss: 1175713.5000 - val_mae: 750.8649 - val_mape: 50.1778
Epoch 45/200

427/427 [==============================] - 1s 3ms/step - loss: 1176362.6250 - mae: 763.2025 - mape: 55.8858 - val_loss: 1144282.6250 - val_mae: 748.7341 - val_mape: 55.4345
Epoch 46/200
427/427 [==============================] - 1s 3ms/step - loss: 1175622.7500 - mae: 761.2576 - mape: 55.4616 - val_loss: 1153410.8750 - val_mae: 758.9897 - val_mape: 58.3955
Epoch 47/200
427/427 [==============================] - 1s 3ms/step - loss: 1178848.3750 - mae: 762.9459 - mape: 55.2390 - val_loss: 1146911.8750 - val_mae: 749.8068 - val_mape: 52.6649
Epoch 48/200
427/427 [==============================] - 1s 3ms/step - loss: 1182181.6250 - mae: 764.7332 - mape: 56.3195 - val_loss: 1158222.1250 - val_mae: 763.5031 - val_mape: 60.7427
Epoch 49/200
427/427 [==============================] - 1s 3ms/step - loss: 1178178.6250 - mae: 763.0427 - mape: 55.3981 - val_loss: 1148519.5000 - val_mae: 752.6644 - val_mape: 56.6204
Epoch 50/200
427/427 [==============================] - 1s 3ms/step - loss: 1168825.1250 - mae: 759.3727 - mape: 55.1005 - val_loss: 1260772.6250 - val_mae: 776.0490 - val_mape: 52.1842
Epoch 51/200
427/427 [==============================] - 1s 2ms/step - loss: 1179174.5000 - mae: 764.8661 - mape: 55.8595 - val_loss: 1182584.8750 - val_mae: 755.1950 - val_mape: 51.8142
Epoch 52/200
427/427 [==============================] - 1s 3ms/step - loss: 1176084.3750 - mae: 758.9773 - mape: 55.0905 - val_loss: 1168923.0000 - val_mae: 769.7318 - val_mape: 61.7754
Epoch 53/200
427/427 [==============================] - 1s 3ms/step - loss: 1172897.6250 - mae: 759.2169 - mape: 55.2372 - val_loss: 1192251.2500 - val_mae: 784.4095 - val_mape: 65.5783
Epoch 54/200
427/427 [==============================] - 1s 3ms/step - loss: 1174245.7500 - mae: 761.0120 - mape: 55.6366 - val_loss: 1143579.5000 - val_mae: 748.6847 - val_mape: 54.3980
Epoch 55/200
427/427 [==============================] - 1s 3ms/step - loss: 1175839.8750 - mae: 760.4958 - mape: 55.1109 - val_loss: 1159863.6250 - val_mae: 762.1855 - val_mape: 58.5314
Epoch 56/200
427/427 [==============================] - 1s 3ms/step - loss: 1172647.0000 - mae: 758.2296 - mape: 54.9232 - val_loss: 1160760.6250 - val_mae: 751.5336 - val_mape: 54.0229
Epoch 57/200
427/427 [==============================] - 1s 3ms/step - loss: 1175296.7500 - mae: 759.0530 - mape: 54.9425 - val_loss: 1142615.8750 - val_mae: 752.4804 - val_mape: 56.9083
Epoch 58/200
427/427 [==============================] - 1s 3ms/step - loss: 1164939.1250 - mae: 755.6251 - mape: 54.6179 - val_loss: 1153635.8750 - val_mae: 765.9764 - val_mape: 62.2544
Epoch 59/200
427/427 [==============================] - 1s 3ms/step - loss: 1176408.0000 - mae: 761.6670 - mape: 55.0462 - val_loss: 1151227.1250 - val_mae: 748.0496 - val_mape: 52.5607
Epoch 60/200
427/427 [==============================] - 1s 3ms/step - loss: 1173878.7500 - mae: 759.4778 - mape: 54.9492 - val_loss: 1340047.7500 - val_mae: 793.1207 - val_mape: 52.2366
Epoch 61/200
427/427 [==============================] - 1s 3ms/step - loss: 1179866.8750 - mae: 761.3947 - mape: 55.5514 - val_loss: 1137399.6250 - val_mae: 747.1038 - val_mape: 53.3627
Epoch 62/200
427/427 [==============================] - 1s 3ms/step - loss: 1174521.5000 - mae: 760.1658 - mape: 54.7949 - val_loss: 1157617.3750 - val_mae: 762.5189 - val_mape: 60.4820
Epoch 63/200
427/427 [==============================] - 1s 3ms/step - loss: 1171544.7500 - mae: 759.1544 - mape: 55.6186 - val_loss: 1174109.2500 - val_mae: 750.2341 - val_mape: 48.9334
Epoch 64/200
427/427 [==============================] - 1s 3ms/step - loss: 1172653.8750 - mae: 757.9743 - mape: 54.7595 - val_loss: 1146358.8750 - val_mae: 749.6039 - val_mape: 54.2056
Epoch 65/200
427/427 [==============================] - 1s 3ms/step - loss: 1166596.6250 - mae: 756.0068 - mape: 54.7150 - val_loss: 1167604.1250 - val_mae: 750.3469 - val_mape: 52.4655
Epoch 66/200
427/427 [==============================] - 1s 3ms/step - loss: 1177981.1250 - mae: 762.2016 - mape: 55.5013 - val_loss: 1148992.7500 - val_mae: 744.9681 - val_mape: 51.4535
Epoch 67/200
427/427 [==============================] - 1s 3ms/step - loss: 1165616.0000 - mae: 754.5563 - mape: 54.7719 - val_loss: 1146876.1250 - val_mae: 761.0959 - val_mape: 62.8591
Epoch 68/200
427/427 [==============================] - 1s 2ms/step - loss: 1169485.6250 - mae: 759.5131 - mape: 55.4128 - val_loss: 1138481.8750 - val_mae: 744.7142 - val_mape: 53.3425
Epoch 69/200
427/427 [==============================] - 1s 3ms/step - loss: 1167707.2500 - mae: 756.9327 - mape: 54.7479 - val_loss: 1184009.2500 - val_mae: 766.1290 - val_mape: 57.8829
Epoch 70/200
427/427 [==============================] - 1s 3ms/step - loss: 1169008.2500 - mae: 757.0048 - mape: 55.3055 - val_loss: 1130743.2500 - val_mae: 747.1520 - val_mape: 56.0000
Epoch 71/200
427/427 [==============================] - 1s 3ms/step - loss: 1167272.1250 - mae: 754.9032 - mape: 54.4701 - val_loss: 1146011.3750 - val_mae: 756.5994 - val_mape: 58.6616
Epoch 72/200
427/427 [==============================] - 1s 3ms/step - loss: 1165725.0000 - mae: 756.9925 - mape: 55.0633 - val_loss: 1132070.0000 - val_mae: 744.5375 - val_mape: 52.0648
Epoch 73/200
427/427 [==============================] - 1s 3ms/step - loss: 1163053.3750 - mae: 754.2362 - mape: 54.3088 - val_loss: 1141887.5000 - val_mae: 747.8356 - val_mape: 53.5988
Epoch 74/200
427/427 [==============================] - 1s 3ms/step - loss: 1172241.0000 - mae: 757.5333 - mape: 55.0753 - val_loss: 1148160.5000 - val_mae: 744.6640 - val_mape: 51.1189
Epoch 75/200
427/427 [==============================] - 1s 3ms/step - loss: 1170052.3750 - mae: 757.8235 - mape: 55.0702 - val_loss: 1140663.2500 - val_mae: 748.2066 - val_mape: 53.8157
Epoch 76/200
427/427 [==============================] - 1s 3ms/step - loss: 1171842.1250 - mae: 756.4200 - mape: 55.0544 - val_loss: 1181936.7500 - val_mae: 762.2090 - val_mape: 56.2294
Epoch 77/200
427/427 [==============================] - 1s 3ms/step - loss: 1164800.2500 - mae: 756.0528 - mape: 54.8984 - val_loss: 1142250.2500 - val_mae: 752.4216 - val_mape: 56.0286
Epoch 78/200
427/427 [==============================] - 1s 2ms/step - loss: 1169505.1250 - mae: 759.2173 - mape: 55.0416 - val_loss: 1138771.5000 - val_mae: 747.1279 - val_mape: 52.9045
Epoch 79/200
427/427 [==============================] - 1s 3ms/step - loss: 1170853.0000 - mae: 756.1240 - mape: 54.4166 - val_loss: 1159348.7500 - val_mae: 748.9406 - val_mape: 52.6175
Epoch 80/200
427/427 [==============================] - 1s 3ms/step - loss: 1164409.0000 - mae: 755.7972 - mape: 55.2309 - val_loss: 1196210.7500 - val_mae: 783.8715 - val_mape: 64.2929

# Now evalutaing test data

In [57]:
test_data = pd.read_csv("test.csv")
test_data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3

In [58]:
test_data.isnull().sum()

Item_Identifier                 0
Item_Weight                   976
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1606
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

# Handling null value of test data

In [59]:
test_data["Outlet_Size"].fillna(test_data["Outlet_Size"].mode()[0], inplace=True)
test_data["Item_Weight"].fillna(test_data["Item_Weight"].mean(), inplace=True)
test_data["Outlet_Establishment_Year"] = test_data["Outlet_Establishment_Year"].astype(str)

# preprocessing of test data

In [60]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

cat_columns = [ 'Item_Fat_Content', 
       'Item_Type', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type']

for val in  cat_columns:
    test_data[val]=label_encoder.fit_transform(test_data[val])

In [61]:
X_test = test_data.drop(columns=["Item_Identifier"])

In [62]:
predictions = model.predict(X_test)

178/178 [==============================] - 0s 2ms/step

In [64]:
test_data["Item_Outlet_Sales_Pred"] = predictions

In [65]:
sam_sub=pd.read_csv("sample_submission.csv")

In [66]:
sam_sub["Item_Outlet_Sales"] = predictions

In [67]:
sam_sub.to_csv("sample_sub_pred.csv",index=False)

In [68]:
test = pd.read_csv("sample_sub_pred.csv")

In [69]:
test.head()

  Item_Identifier Outlet_Identifier  Item_Outlet_Sales
0           FDW58            OUT049         1709.20780
1           FDW14            OUT017         1484.22450
2           NCN55            OUT010          562.63477
3           FDQ58            OUT017         2533.15620
4           FDY38            OUT027         5987.64940

In [63]:
count=0
for val in predictions :
    if val < 0:
        print(val)
        count=count+1
print(count)

0

In [ ]:
coun